server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.31.252:8848
      config:
        namespace: online
        group: online

  config:
    import:
      - nacos:gateway.yml